name: Deploy to Apache2 Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Apache2
      run: |
        sudo apt-get update
        sudo apt-get install apache2 -y
        sudo service apache2 start

    - name: Copy HTML Project to Apache2 Document Root
      run: |
        sudo cp -r * /var/www/html/

    - name: Set Permissions (adjust as needed)
      run: |
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html
        
    - name: Set up SSH and deploy
      run: |
        eval "$(SSH_AGENT_S)"
        ssh-add <(echo "$SSH_PRIVATE_KEY")
        scp -r ./html/* ubuntu@65.2.168.216:/var/www/html/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Restart Apache on Remote Server
      run: |
        sudo service apache2 restart

